name: AntiHunger
version: ${project.version}
main: me.regos.antihunger.AntiHunger
api-version: 1.16
commands:
  hungertoggle:
    description: Turn on/off the hunger change event
    usage: /<command>
